### ISSUE TITLE
[ENHANCEMENT]: Avoiding the redundant/extra arithmetic operations

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/contracts#1]
## BUG DESC.:
https://github.com/sunflower-land/contracts/blob/e8c8370aec41ecc50924fa1c966d1cebb9843dfa/contracts/Beta.sol#L58
 
In above calculation redundant/ extra arithmetic operations are performed.

Any thoughts on this ?

## BUG SCOPE: 
Performance and (or) Processing Time

## SUGGESTIONS: 😄 

i.e. Why not write its directly as below ?
```solidity
uint teamAmount = amount * 9 / 10; 
```

or most<sup>[1]</sup> efficiently;

```solidity
uint teamAmount = amount * 0.9; 
```

And, I guess the performance of the contracts is directly related to the time required for completing the tx.
Also, benchmarking these operations in various languages shows ~2% difference.

> [1]: _it's not until solidity performs kind of bit shifting and (or) use any magic numbers behind the scenes 👀  , like most of compilers incorporate such methods for code and performance optimizations_

---

PS: I'm just getting started with solidity, web3 and blockchain domains 😇

**Comment by adamhannigan** [comment]
Good feedback 👏 

The main reason behind this was that we wanted to make it clear that it was `90%`. `9/10` could be used as well.

`uint teamAmount = amount * 0.9; `

You are about to have a lot of fun: Decimals don't exist in solidity 😱 We need to invent our own constructs for floating number support.

**Comment by Pranav-yadav** [comment]
> Good feedback 👏
> 
> The main reason behind this was that we wanted to make it clear that it was `90%`. `9/10` could be used as well.
> 
> `uint teamAmount = amount * 0.9; `
> 
> You are about to have a lot of fun: Decimals don't exist in solidity 😱 We need to invent our own constructs for floating number support.

😱 my bad.
Btw, it's effect of my exhaustive coding in HLL's (C, C++, Java, etc.) Especially optimizing C/C++ programs using bit shifting and hacks 🤓  to avoid some calculations. 😃

Interesting...
I should complete the basics of Solidity whenever I get time. Tho, I want to get my hands dirty with Rust :)
