### ISSUE TITLE
[ENHANCEMENT]: Avoiding alias for data types

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-land/contracts#2]
After, going through fun sign 's and code, I have seen extensive use of **alias** for data types at many places, specifically;
`uint` for `uint256`
(_yep, they mean the same but, ..._)

There are countless merits of explicitness 👍 

Now, If we want these contracts to be future proof (talking about LTE of Blockchain(s)), alias must be avoided wherever possible.
(_yep, the blockchain dev's aren't dumb and will try to provide LTS as long as possible_)

From my little bit reading on possible demerits of alias, (in case of `uint` for `uint256` and similar ones) Smart Contracts will *only* understand the explicit ones when comparing method sign id's 👀 .

@fabioelizandro @adamhannigan What are your views on this ?

PS: I've recently began to explore and learn about blockchain so, please correct me wherever possible.
Just putting my thoughts under issues, as Discussions are not enabled for this repo.

**Comment by adamhannigan** [comment]
@Pranav-yadav I missed this comment, apologies for the delay.

It wouldn't produce a vulnerability in this case due do the use case in the code and solidity's casting of numbers.

However you raise a good point. We should be consistent with our use of data types, especially when we start iterating and using these values for other purposes/features 👏

**Comment by Pranav-yadav** [comment]
Agreed. Definitely it should not produce any vulnerability. As the title suggests and you pointed earlier, it's re: consistency.
Thanks for sharing your understandings.

Though, I'm waiting for Fabio's insights on this 😇
